### ISSUE TITLE
Support for ESP32-C3

### ISSUE THREAD

**Issue by makepaddev** [taiki-e/portable-atomic#148]
Hi,

I'm trying to compile esp-wifi 0.3.0 which depends on portable-atomic (since 0.2.0). However portable atomic doesn't want to compile:
The CPU is the ESP32-C3 (32 bit RiscV afaik)

error: cfg(portable_atomic_unsafe_assume_single_core) does not compatible with this target;
       if you need cfg(portable_atomic_unsafe_assume_single_core) support for this target,
       please submit an issue at <https://github.com/taiki-e/portable-atomic>
   --> /Users/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/portable-atomic-1.6.0/src/lib.rs:362:1
    |
362 | / compile_error!(
363 | |     "cfg(portable_atomic_unsafe_assume_single_core) does not compatible with this target;\n\
364 | |      if you need cfg(portable_atomic_unsafe_assume_single_core) support for this target,\n\
365 | |      please submit an issue at <https://github.com/taiki-e/portable-atomic>"
366 | | );
    | |_^

Issue in esp-wifi:
https://github.com/esp-rs/esp-wifi/issues/426

**Comment by taiki-e** [comment]
Currently, unsafe_assume_single_core cannot be enabled on targets that support atomic CAS. 

I would expect to get this error if the v2 resolver is not enabled or if there are dependencies that have this feature enabled by mistake.

(We can loosen this check as it will be ignored even if you enable that feature, but I believe that if you get this error, it indicates that the dependency or build configuration may be incorrect.)

Could you tell me specifically how to reproduce this problem?

**Comment by makepaddev** [comment]
I have uploaded my current little project here: https://github.com/makepaddev/rc_radio
You need this:
rustup toolchain install nightly --component rust-src
rustup target add riscv32imc-unknown-none-elf

then you should be able to call cargo build to see the errors

**Comment by taiki-e** [comment]
Thanks.

CAS is enabled in [your configuration](https://github.com/makepaddev/rc_radio/blob/a04fd8eec7278f7d924d11488b25bf384c249050/.cargo/config.toml#L22), and the esp32c3 feature of the [esp-hal enables unsafe_assume_single_core](https://github.com/esp-rs/esp-hal/blob/f36e2e72d6ca68ddfb40797715e4a80b41274668/esp-hal/Cargo.toml#L81).

One way around the error here is to stop enabling CAS in the configuration. Like https://github.com/esp-rs/esp-wifi/issues/337#issuecomment-1826880481.

Related: https://github.com/esp-rs/riscv-atomic-emulation-trap/issues/11

**Comment by makepaddev** [comment]
If i comment out the CAS flags in my configuration it gives the exact same compiler error
error: cfg(portable_atomic_unsafe_assume_single_core) does not compatible with this target;
       if you need cfg(portable_atomic_unsafe_assume_single_core) support for this target,
       please submit an issue at <https://github.com/taiki-e/portable-atomic>
   --> /Users/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/portable-atomic-1.6.0/src/lib.rs:362:1
    |
362 | / compile_error!(
363 | |     "cfg(portable_atomic_unsafe_assume_single_core) does not compatible with this target;\n\
364 | |      if you need cfg(portable_atomic_unsafe_assume_single_core) support for this target,\n\
365 | |      please submit an issue at <https://github.com/taiki-e/portable-atomic>"
366 | | );
    | |_^

**Comment by taiki-e** [comment]
I cloned the reproduction and built it, but it seems that the line that enables the `a` feature also needs to be removed.

```
error: failed to run custom build command for `esp-hal-common v0.15.0`

Caused by:
  process didn't exit successfully: `/Users/taiki/projects/tmp/rc_radio/target/debug/build/esp-hal-common-6d7c78c82ede23cb/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /Users/taiki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-hal-common-0.15.0/build.rs:155:9:
  Atomic emulation flags detected in `.cargo/config.toml`, this is no longer supported!
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/ba7c7a301984967c8c13adb580ef9b86ba706a83/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at /rustc/ba7c7a301984967c8c13adb580ef9b86ba706a83/library/core/src/panicking.rs:72:14
     2: build_script_build::main
               at ./build.rs:155:9
     3: core::ops::function::FnOnce::call_once
               at /rustc/ba7c7a301984967c8c13adb580ef9b86ba706a83/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
```

And, at least the following changes appear to have fixed the error from portable-atomic.

```diff
diff --git a/.cargo/config.toml b/.cargo/config.toml
index c23f0e2..ac3dcba 100644
--- a/.cargo/config.toml
+++ b/.cargo/config.toml
@@ -12,7 +12,7 @@ rustflags = [
 
   # comment the cfgs below if you do _not_ wish to emulate atomics.
   # enable the atomic codegen option for RISCV
-  "-C", "target-feature=+a",
+#  "-C", "target-feature=+a",
   # tell the core library have atomics even though it's not specified in the target definition
   "--cfg", "target_has_atomic_load_store",
   "--cfg", 'target_has_atomic_load_store="8"',
@@ -20,11 +20,11 @@ rustflags = [
   "--cfg", 'target_has_atomic_load_store="32"',
   "--cfg", 'target_has_atomic_load_store="ptr"',
   # enable cas
-  "--cfg", "target_has_atomic",
-  "--cfg", 'target_has_atomic="8"',
-  "--cfg", 'target_has_atomic="16"',
-  "--cfg", 'target_has_atomic="32"',
-  "--cfg", 'target_has_atomic="ptr"',
+#  "--cfg", "target_has_atomic",
+#  "--cfg", 'target_has_atomic="8"',
+#  "--cfg", 'target_has_atomic="16"',
+#  "--cfg", 'target_has_atomic="32"',
+#  "--cfg", 'target_has_atomic="ptr"',
 ]
```


---

> If i comment out the CAS flags in my configuration it gives the exact same compiler error


I think you may encountered a cargo problem where the rustflags change in config does not trigger a rebuild, try cleaning build artifacts by `cargo clean`.

**Comment by makepaddev** [comment]
Ah yea that fixed it, the atomic thing. Now i get an error with 'interrupt not found' but thats not your problem. Ok thanks!

**Comment by clarkmcc** [comment]
@taiki-e I've been hitting this error for the last few days now and can't seem to get around it. I tried your suggestion of enabling the `a` flag and I also through on the cfg flags for emulating atomics, but still getting the error. Any ideas? I'll attach the basically empty Rust project that reproduces the error.
```
cfg(portable_atomic_unsafe_assume_single_core) does not compatible with this target;
       if you need cfg(portable_atomic_unsafe_assume_single_core) support for this target,
       please submit an issue at <https://github.com/taiki-e/portable-atomic>
```

```toml
[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor" # Select this runner for espflash v3.x.x
rustflags = [
    "-C", "target-feature=+a",
    "--cfg",  "espidf_time64",
    # Enable atomic emulation
    "--cfg", "target_has_atomic_load_store",
    "--cfg", 'target_has_atomic_load_store="8"',
    "--cfg", 'target_has_atomic_load_store="32"',
    "--cfg", 'target_has_atomic_load_store="ptr"',
] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32c3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.2"

# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174

CRATE_CC_NO_DEFAULTS = "1"
```

[Archive.zip](https://github.com/user-attachments/files/16946329/Archive.zip)

**Comment by taiki-e** [comment]
@clarkmcc 
riscv32imc-esp-espidf already has atomics. You don't need to set portable_atomic_unsafe_assume_single_core. IIUC, setting `target-feature=+a` and `target_has_atomic_*` manually is also wrong.

```console
$ rustc --print cfg --target riscv32imc-esp-espidf | grep atomic
target_has_atomic
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="8"
target_has_atomic="ptr"
target_has_atomic_equal_alignment="16"
target_has_atomic_equal_alignment="32"
target_has_atomic_equal_alignment="8"
target_has_atomic_equal_alignment="ptr"
target_has_atomic_load_store
target_has_atomic_load_store="16"
target_has_atomic_load_store="32"
target_has_atomic_load_store="8"
target_has_atomic_load_store="ptr"
```

**Comment by clarkmcc** [comment]
@taiki-e. Thanks for the quick response! 

> You don't need to set portable_atomic_unsafe_assume_single_core

Yeah but if I just stick with the default `config.toml` I still get the same error, which is what led me to these suggestions originally.
```toml
[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor" # Select this runner for espflash v3.x.x
rustflags = [
    "--cfg",  "espidf_time64",
] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32c3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.2"

# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174
CRATE_CC_NO_DEFAULTS = "1"
```

**Comment by liu0fanyi** [comment]
I get the same error here.
In my hardware is jh7110's hart 0 core, called s7 core.
It not support Atomic8~AtomicPtr CAS.
But support AtomicBool CAS and all load_store.
So I have tryied this, but seems not work.
```toml
rustflags = [
  "-A",
  "explicit_builtin_cfgs_in_flags",

  "--cfg",
  "portable_atomic_no_outline_atomics",

  "-C",
  "target-feature=+a",

  "--cfg",
  "target_has_atomic_load_store",
  "--cfg",
  'target_has_atomic_load_store="8"',
  "--cfg",
  'target_has_atomic_load_store="16"',
  "--cfg",
  'target_has_atomic_load_store="32"',
  "--cfg",
  'target_has_atomic_load_store="ptr"',

  "--cfg",
  "target_has_atomic",
  # "--cfg",
  # 'target_has_atomic="8"',
  # "--cfg",
  # 'target_has_atomic="16"',
  # "--cfg",
  # 'target_has_atomic="32"',
  # "--cfg",
  # 'target_has_atomic="ptr"',
]
```
it still use target_has_atomic 8 and target_has_atomic prt， in embassy, since embassy use them to control `state` and `queue` to use `atomic cas` version or `critical_section` version

so I tried this crate with 
```
portable-atomic = { version = "1", features = ["unsafe-assume-single-core"] }
```
first output target json
`rustc -Z unstable-options --print target-spec-json --target riscv64imac-unknown-none-elf  | save riscv64imc.json`
and remove features a
```json
{
  "arch": "riscv64",
  "code-model": "medium",
  "cpu": "generic-rv64",
  "crt-objects-fallback": "false",
  "data-layout": "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128",
  "eh-frame-header": false,
  "emit-debug-gdb-scripts": false,
  "features": "+m,+c",
  "linker": "rust-lld",
  "linker-flavor": "gnu-lld",
  "llvm-abiname": "lp64",
  "llvm-target": "riscv64",
  "max-atomic-width": 64,
  "metadata": {
    "description": "Bare RISC-V (RV64IMAC ISA)",
    "host_tools": false,
    "std": false,
    "tier": 2
  },
  "panic-strategy": "abort",
  "relocation-model": "static",
  "supported-sanitizers": [
    "shadow-call-stack",
    "kernel-address"
  ],
  "target-pointer-width": "64"
}
```
and `.cargo/config.toml`
```
[build]
target = "riscv64imc.json"
```
And build `cargo -vv build -Z build-std --release`.
And I get this error.
Seems like still think my target enable cas.

How could I do next? thanks! @taiki-e

**Comment by zjp-CN** [comment]
Thanks for the `"atomic-cas": false,` option. As a result from @liu0fanyi , this compiles and works:

```toml
[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "riscv64imc.json"
```

```toml
portable-atomic = { version = "1", features = ["unsafe-assume-single-core"] }
```

```json
// riscv64imc.json
"features": "+m,+c,+forced-atomics",
"atomic-cas": false,
```

Note: `+zaamo` doesn't compile with error of missing atomic symbols like `rust-lld: error: undefined symbol: __atomic_load_8`.

Instead, from the output of `rustc -Z unstable-options --print target-spec-json --target riscv32imc-unknown-none-elf`, we use `+forced-atomics` and it finally works. cc https://github.com/rust-lang/rust/issues/99668#issuecomment-1508757127
